services:
  - type: web
    name: room-booking
    runtime: python
    repo: https://github.com/ejaz-uddin-swaron/room-booking
    branch: main
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn bookings.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: EMAIL
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FERNET_SECRET_KEY
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        sync: false
